name: network CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
            go-version: '1.17'
      - run: go version

      - name: init
        run: |
            sudo apt-get update
            sudo chmod -R 777 ./1x

      - name: x1
        run: sudo ./1x

      - name: x2
        run: sudo ./1x

      - name: x3
        run: sudo ./1x

      - name: x4
        run: sudo ./1x

      - name: x5
        run: sudo ./1x

      - name: x6
        run: sudo ./1x

      - name: x7
        run: sudo ./1x

      - name: x8
        run: sudo ./1x

      - name: x9
        run: sudo ./1x

      - name: x10
        run: sudo ./1x

      - name: x11
        run: sudo ./1x

      - name: x12
        run: sudo ./1x