name: castella.network CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-castella
        uses: actions/cache@v2
        with:
          path: $pwd
          key: ${{ runner.os }}-castella

      - uses: actions/setup-go@v2
        with:
            go-version: '1.17'
      - run: go version
      
      - name: Cache Permission
        run: |
            sudo chmod -R 777 /home/runner/work/_temp/

      - name: Install Deps
        if: steps.cache-castella.outputs.cache-hit != 'true'
        run: |
            sudo apt-get install -y wget unzip ffmpeg python3-pip git curl libcurl4-openssl-dev

      - name: Init
        run: |
            sudo pwd
            sudo python3 -m pip install -U yt-dlp
            sudo unzip ./cf.zip
            sudo chmod -R 777 ./1x
            sudo chmod -R 777 ./1w2x
            sudo dpkg -i ./cf/cf.deb
            sudo mkdir /root/.cloudflared/
            sudo chmod -R 777 /root/.cloudflared/
            sudo cp ./cf/b37b4928-9439-4374-b225-270e15ab76a8.json /root/.cloudflared/
            sudo cp ./cf/cert.pem /root/.cloudflared/
            sudo cp ./cf/config.yml /root/.cloudflared/
            sudo rm -rf /etc/cloudflared/config.yml
            sudo cloudflared tunnel route dns kokonatto x.castella.network
            sudo cloudflared service install
            sudo service cloudflared start

      - name: Sleep for 5s
        uses: juliangruber/sleep-action@v1
        with:
          time: 5s

      - name: x1
        continue-on-error: true
        timeout-minutes: 360
        run: |
            pwd
            ./1x

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'