name: network CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
            sudo apt-get update
            sudo apt-get install -y wget
            sudo wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.5.linux-amd64.tar.gz
            sudo export PATH=$PATH:/usr/local/go/bin
            sudo go version
            sudo chmod -R 777 ./1x

      - name: x1
        run: sudo ./1x

      - name: x2
        run: sudo ./1x

      - name: x3
        run: sudo ./1x

      - name: x4
        run: sudo ./1x

      - name: x5
        run: sudo ./1x

      - name: x6
        run: sudo ./1x

      - name: x7
        run: sudo ./1x

      - name: x8
        run: sudo ./1x

      - name: x9
        run: sudo ./1x

      - name: x10
        run: sudo ./1x

      - name: x11
        run: sudo ./1x

      - name: x12
        run: sudo ./1x