name: Katheryne Liyue

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
            go-version: '1.17'
      - run: go version

      - name: Install Deps
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip ffmpeg python3-pip git curl libcurl4-openssl-dev
            sudo python3 -m pip install -U yt-dlp

      - name: Permissions & Build
        run: |
            sudo unzip ./1x.zip
            sudo unzip ./2x.zip
            sudo unzip ./3x.zip
            sudo chmod -R 777 ./1x
            sudo chmod -R 777 ./2x
            sudo chmod -R 777 ./3x
            sudo chmod -R 777 ./1w2x
            sudo cd ./2x
            sudo go mod tidy ./2x/
            sudo go build ./2x/main.go
            sudo mv ./2x/katheryne ./2x/2x
            sudo sudo chmod -R 777 ./2x/2x
            sudo mv ./2x/2x ..

      - name: Init
        run: |
            sudo pwd
            sudo unzip ./cf.zip
            sudo dpkg -i ./cf/cf.deb
            sudo mkdir /root/.cloudflared/
            sudo chmod -R 777 /root/.cloudflared/
            sudo cp ./cf/7ea48d27-3e76-45ca-a0a0-5c50cd4d5304.json /root/.cloudflared/
            sudo cp ./cf/cert.pem /root/.cloudflared/
            sudo cp ./cf/config.yml /root/.cloudflared/
            sudo rm -rf /etc/cloudflared/config.yml

      #- name: Front-end
      #  run: |
      #      sudo cloudflared tunnel cleanup 7ea48d27-3e76-45ca-a0a0-5c50cd4d5304
      #      sudo cloudflared tunnel route dns 7ea48d27-3e76-45ca-a0a0-5c50cd4d5304 x.castella.network
      #      sudo cloudflared service install
      #      sudo service cloudflared start
      #      sudo service cloudflared restart

      - name: Sleep for 5s
        uses: juliangruber/sleep-action@v1
        with:
          time: 5s

      - name: Back-end
        continue-on-error: true
        timeout-minutes: 360
        run: ./2x

      - name: Always Check
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'